### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by egoarka** [jhipster/prettier-java#110]
After processing prettier on this file
https://github.com/egoarka/itmo-oop/blob/master/lab5/app/src/main/java/com/attributes/XmlAttribute.java

it gives me the error
```
XmlAttribute.java
[error] XmlAttribute.java: TypeError: Cannot read property 'type' of undefined
[error]     at printNode (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier-plugin-java/src/printer.js:2253:16)
[error]     at Object.genericPrint [as print] (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier-plugin-java/src/printer.js:2700:10)
[error]     at callPluginPrintFunction (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13503:18)
[error]     at /home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13454:16
[error]     at Object.printComments (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13188:17)
[error]     at printGenerically (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13453:22)
[error]     at FastPath.call (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13299:16)
[error]     at printAnnotationMethodRest (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier-plugin-java/src/printer.js:282:18)
[error]     at printNode (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier-plugin-java/src/printer.js:2279:14)
[error]     at Object.genericPrint [as print] (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier-plugin-java/src/printer.js:2700:10)
[error]     at callPluginPrintFunction (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13503:18)
[error]     at /home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13454:16
[error]     at Object.printComments (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13188:17)
[error]     at printGenerically (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13453:22)
[error]     at FastPath.call (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier/bin-prettier.js:13299:16)
[error]     at printAnnotationTypeElementRest (/home/user/.nvm/versions/node/v11.3.0/lib/node_modules/prettier-plugin-java/src/printer.js:264:18)

```

**Comment by bd82** [comment]
This project is being re-written.
Please watch the project and re-examine if your issue still exists once there would be a new alpha version.
