### ISSUE TITLE
Error while parsing integers with underscores

### ISSUE THREAD

**Issue by n-peugnet** [jhipster/prettier-java#210]
Hi I am currently testing the prettier-java plugin. I had some errors while applying prettier on my files:

```
src/main/java/com/dant/utils/Utils.java
[error] src/main/java/com/dant/utils/Utils.java: Error: Sad sad panda, parsing errors detected in line: 44, column: 45!
[error] Expecting: one of these possible Token sequences:
[error]   1. ['->']
[error]   2. ['*']
[error]   3. ['/']
[error]   4. ['%']
[error]   5. ['+']
[error]   6. ['-']
[error]   7. ['<<']
[error]   8. ['<=']
[error]   9. ['>=']
[error]   10. ['>']
[error]   11. ['<']
[error]   12. ['==']
[error]   13. ['!=']
[error]   14. ['&']
[error]   15. ['^']
[error]   16. ['|']
[error]   17. ['&&']
[error]   18. ['||']
[error]   19. ['=']
[error]   20. ['+=']
[error]   21. ['-=']
[error]   22. ['*=']
[error]   23. ['/=']
[error]   24. ['&=']
[error]   25. ['|=']
[error]   26. ['^=']
[error]   27. ['>>=']
[error]   28. ['>>>=']
[error]   29. ['<<=']
[error]   30. ['%=']
[error]   31. [Identifier]
[error]   32. ['this']
[error]   33. ['super']
[error]   34. ['DecimalLiteral']
[error]   35. ['HexLiteral']
[error]   36. ['OctLiteral']
[error]   37. ['BinaryLiteral']
[error]   38. ['FloatLiteral']
[error]   39. ['HexFloatLiteral']
[error]   40. ['CharLiteral']
[error]   41. ['StringLiteral']
[error]   42. ['true']
[error]   43. ['false']
[error]   44. ['null']
[error]   45. ['@']
[error]   46. ['boolean']
[error]   47. ['char']
[error]   48. ['byte']
[error]   49. ['short']
[error]   50. ['int']
[error]   51. ['long']
[error]   52. ['float']
[error]   53. ['double']
[error]   54. ['void']
[error]   55. ['new']
[error]   56. ['++']
[error]   57. ['--']
[error]   58. ['~']
[error]   59. ['!']
[error]   60. ['(']
[error]   61. ['.']
[error]   62. ['?']
[error]   63. []
[error] but found: ';'
[error]     at Object.parse (/home/nicolas/Source/java/slipdb/node_modules/chevrotain-java/src/index.js:20:11)
[error]     at Object.parse (/home/nicolas/Source/java/slipdb/node_modules/prettier-plugin-java/src/parser.js:6:25)
[error]     at Object.parse$2 [as parse] (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:10631:19)
[error]     at coreFormat (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:13890:23)
[error]     at format (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:14148:73)
[error]     at formatWithCursor (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:14164:12)
[error]     at Object.formatWithCursor (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:42758:15)
[error]     at format$1 (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:44127:21)
[error]     at /home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:44322:16
[error]     at /home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:44262:14
[error]     at Array.forEach (<anonymous>)
[error]     at eachFilename (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:44261:15)
[error]     at Object.formatFiles (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:44283:3)
[error]     at Object.run (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:44840:14)
[error]     at Object.<anonymous> (/home/nicolas/Source/java/slipdb/node_modules/prettier/bin-prettier.js:44855:5)
[error]     at Module._compile (internal/modules/cjs/loader.js:776:30)
```

Here is the line 44:
```java
			return (int) (tempDate.getTime() / 1_000);
```

I tried to write `1000` instead of `1_000` and it solved the problem.
The full file [can be found here](https://github.com/slipsoft/slipdb/blob/f21eaa8db1650a4b267f0211f5e4b254d459c53a/src/main/java/com/dant/utils/Utils.java).

**Comment by clement26695** [comment]
Same as in #211.

I close the issue as it is resolved on the current version of master.
