### ISSUE TITLE
Error parsing a string containing a single quote following a char

### ISSUE THREAD

**Issue by bfabry** [jhipster/prettier-java#212]
Minimal test case:
```
public class Test {
  public static void main(String[] args) {
    char datadogJobName = '.';
    String val = "str'ing";
  }
}
```

Output:
```
Test.java
[error] Test.java: Error: Sad sad panda, parsing errors detected in line: 4, column: 23!
[error] Expecting: one of these possible Token sequences:
[error]   1. [';']
[error]   2. [';']
[error] but found: 'ing'
[error]     at Object.parse (/Users/bfabry/Code/zendesk/data_lake/node_modules/chevrotain-java/src/index.js:20:11)
[error]     at Object.parse (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier-plugin-java/src/parser.js:6:25)
[error]     at Object.parse$2 [as parse] (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:10631:19)
[error]     at coreFormat (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:13890:23)
[error]     at format (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:14148:73)
[error]     at formatWithCursor (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:14164:12)
[error]     at Object.formatWithCursor (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:42758:15)
[error]     at format$1 (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:44127:21)
[error]     at /Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:44322:16
[error]     at /Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:44262:14
[error]     at Array.forEach (<anonymous>)
[error]     at eachFilename (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:44261:15)
[error]     at Object.formatFiles (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:44283:3)
[error]     at Object.run (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:44840:14)
[error]     at Object.<anonymous> (/Users/bfabry/Code/zendesk/data_lake/node_modules/prettier/bin-prettier.js:44855:5)
[error]     at Module._compile (internal/modules/cjs/loader.js:774:30)
error Command failed with exit code 2.
```

**Comment by clement26695** [comment]
Same as #211 (https://github.com/jhipster/prettier-java/issues/211#issuecomment-501406978)

First of all, many thanks for reporting the issue ! 👍

I tested your code snippet with the current version on master, and everything works well, so I'm closing the issue. We will try to publish the new version on npm really soon !

PS: I arrived at this formatting, FYI: 

```java
public class Test {

  public static void main(String[] args) {
    char datadogJobName = '.';
    String val = "str'ing";
  }
}
```

**Comment by bfabry** [comment]
Ah yes, the problem was my lack of understanding of how node packages work, not the parser. Runs now across our entire codebase with basically no problems. The only errors are on .java files that have been completely block commented out which is probably not a valid project anyway
