### ISSUE TITLE
Parse error on double[][]::new

### ISSUE THREAD

**Issue by victornoel** [jhipster/prettier-java#412]
**Prettier-Java 0.8.0**

**Input:**

```java
import java.util.List;

public class Test {
    public static void main(String[] args) {
        List.of().toArray(double[][]::new);
    }
}
```

**Error:**
```
engine/src/test/java/Test.java
[error] engine/src/test/java/Test.java: Error: Sad sad panda, parsing errors detected in line: 5, column: 37!
[error] Expecting --> '.' <-- but found --> '::' <--!
[error] 	->compilationUnit
[error] 	->ordinaryCompilationUnit
[error] 	->typeDeclaration
[error] 	->classDeclaration
[error] 	->normalClassDeclaration
[error] 	->classBody
[error] 	->classBodyDeclaration
[error] 	->classMemberDeclaration
[error] 	->methodDeclaration
[error] 	->methodBody
[error] 	->block
[error] 	->blockStatements
[error] 	->blockStatement
[error] 	->statement
[error] 	->statementWithoutTrailingSubstatement
[error] 	->expressionStatement
[error] 	->statementExpression
[error] 	->expression
[error] 	->ternaryExpression
[error] 	->binaryExpression
[error] 	->unaryExpression
[error] 	->primary
[error] 	->primarySuffix
[error] 	->methodInvocationSuffix
[error] 	->argumentList
[error] 	->expression
[error] 	->ternaryExpression
[error] 	->binaryExpression
[error] 	->unaryExpression
[error] 	->primary
[error] 	->primarySuffix
[error] 	->classLiteralSuffix
[error]     at Object.parse (/home/victor/.config/yarn/global/node_modules/java-parser/src/index.js:40:11)
[error]     at Object.parse (/home/victor/.config/yarn/global/node_modules/prettier-plugin-java/src/parser.js:6:26)
[error]     at Object.parse (/home/victor/.config/yarn/global/node_modules/prettier/bin-prettier.js:11410:19)
[error]     at coreFormat (/home/victor/.config/yarn/global/node_modules/prettier/bin-prettier.js:14826:25)
[error]     at format (/home/victor/.config/yarn/global/node_modules/prettier/bin-prettier.js:15061:75)
[error]     at formatWithCursor (/home/victor/.config/yarn/global/node_modules/prettier/bin-prettier.js:15077:12)
[error]     at Object.args [as formatWithCursor] (/home/victor/.config/yarn/global/node_modules/prettier/bin-prettier.js:51662:12)
[error]     at format$1 (/home/victor/.config/yarn/global/node_modules/prettier/bin-prettier.js:53707:19)
[error]     at Object.formatFiles (/home/victor/.config/yarn/global/node_modules/prettier/bin-prettier.js:53880:16)
[error]     at Object.run (/home/victor/.config/yarn/global/node_modules/prettier/bin-prettier.js:54336:14)
```

**Expected behavior:**

Nothing specific, just that it doesn't crash :)

**Comment by clementdessoude** [comment]
FYI, I just published the new version :)
