### ISSUE TITLE
Can't generate object 

### ISSUE THREAD

**Issue by Bertpey** [jhipster/prettier-java#465]
Hi, 
J'essaye de générer un projet Jhipster, et j'ai une erreur lors de la génération des entités, 
ERROR! Error parsing file src\main\java\com\mycompany\myapp\repository\RegionRepository.java: Error: Sad sad panda, parsing errors detected in line: 12, column: 43!
Expecting token of type --> Identifier <-- but found --> '<' <--!

Cote .jdl j'ai pris tout simplement celui de https://start.jhipster.tech/jdl-studio/  par défaut, pour tester, et toujours la même erreur.*
J'ai les dernières versions je pense, je suis en 
prettier-plugin-java@1.0.2
java-parser@1.0.2

Error: Error parsing file src\main\java\com\mycompany\myapp\repository\RegionRepository.java: Error: Sad sad panda, parsing errors detected in line: 12, column: 43!
Expecting token of type --> Identifier <-- but found --> '<' <--!
        ->compilationUnit
        ->ordinaryCompilationUnit
        ->typeDeclaration
        ->interfaceDeclaration
        ->normalInterfaceDeclaration
        ->extendsInterfaces
        ->interfaceTypeList
        ->interfaceType
        ->classType
    at Object.parse (C:\developpement\jhipster\test2\node_modules\java-parser\src\index.js:40:11)
    at Object.parse (C:\developpement\jhipster\test2\node_modules\prettier-plugin-java\src\parser.js:6:26)
    at Object.parse (C:\developpement\jhipster\test2\node_modules\prettier\index.js:13625:19)
    at coreFormat (C:\developpement\jhipster\test2\node_modules\prettier\index.js:14899:14)
    at format (C:\developpement\jhipster\test2\node_modules\prettier\index.js:15131:14)
    at C:\developpement\jhipster\test2\node_modules\prettier\index.js:57542:12
    at Object.format (C:\developpement\jhipster\test2\node_modules\prettier\index.js:57562:12)
    at C:\developpement\jhipster\test2\node_modules\generator-jhipster\generators\generator-transforms.js:50:31

At: package com.mycompany.myapp.repository;

import com.mycompany.myapp.domain.Region;

Auriez-vous une idée ?

**Comment by Bertpey** [comment]
probs env
