### ISSUE TITLE
Sad sad panda error with nested sealed classes

### ISSUE THREAD

**Issue by jqno** [jhipster/prettier-java#522]
**Prettier-Java 1.6.0**

I have a class that contains a static sealed class and its static subclasses. When I try to format it, I get a Sad sad panda error.

```sh
# .prettierrc:
tabWidth: 4
printWidth: 100
trailingComma: "none"
```

**Input:**

```java
package nl.jqno.equalsverifier.integration.extended_contract;

public class SealedClasses {
    public static sealed abstract class SealedParent permits SealedChild {}

    final static class SealedChild extends SealedParent {}
}
```

**Output:**

unchanged, but got this error:

```sh
└─❯ prettier SealedClasses.java
SealedClasses.java[error] SealedClasses.java: Error: Sad sad panda, parsing errors detected in line: 4, column: 12!
[error] Expecting token of type --> Identifier <-- but found --> 'static' <--!
[error] 	->compilationUnit
[error] 	->ordinaryCompilationUnit
[error] 	->typeDeclaration
[error] 	->classDeclaration
[error] 	->normalClassDeclaration
[error] 	->classBody
[error] 	->classBodyDeclaration
[error] 	->constructorDeclaration
[error] 	->constructorDeclarator
[error] 	->simpleTypeName
[error]     at Object.parse (/home/jqno/.npm-global/lib/node_modules/prettier-plugin-java/node_modules/java-parser/src/index.js:41:11)
[error]     at Object.parse (/home/jqno/.npm-global/lib/node_modules/prettier-plugin-java/src/parser.js:6:26)
[error]     at Object.parse$a [as parse] (/home/jqno/.npm-global/lib/node_modules/prettier/index.js:13684:19)
[error]     at coreFormat (/home/jqno/.npm-global/lib/node_modules/prettier/index.js:15215:16)
[error]     at formatWithCursor$1 (/home/jqno/.npm-global/lib/node_modules/prettier/index.js:15455:14)
[error]     at Object.formatWithCursor (/home/jqno/.npm-global/lib/node_modules/prettier/index.js:60228:12)
[error]     at format$1 (/home/jqno/.npm-global/lib/node_modules/prettier/bin-prettier.js:16827:21)
[error]     at Object.formatFiles$1 [as formatFiles] (/home/jqno/.npm-global/lib/node_modules/prettier/bin-prettier.js:16941:16)
[error]     at async main (/home/jqno/.npm-global/lib/node_modules/prettier/bin-prettier.js:18802:5)
[error]     at async Object.run (/home/jqno/.npm-global/lib/node_modules/prettier/bin-prettier.js:18745:5)
```

**Expected behavior:**

No error and properly formatted file

**Comment by clementdessoude** [comment]
Thanks for submitting this issue @jqno. #523 should fix it hopefully !

**Comment by jqno** [comment]
Awesome, thanks! I eagerly await the release :smile:

**Comment by pascalgrimaud** [comment]
adding a bounty as it's a bug
should be cool to have it in next release :)

**Comment by clementdessoude** [comment]
Hi there ! I just released the 1.6.1 version. Can you test it @jqno and tell me if the bug is fixed ?

**Comment by jqno** [comment]
Confirmed, it works! Thanks for the quick turnaround!

**Comment by clementdessoude** [comment]
Bounty claimed ! https://opencollective.com/generator-jhipster/expenses/60787 :)

**Comment by pascalgrimaud** [comment]
@clementdessoude : approved
