### ISSUE TITLE
Sad sad panda when formatting code containing a regex ("^\s$")

### ISSUE THREAD

**Issue by marcwrobel** [jhipster/prettier-java#541]
When formatting a java file that contains the following code with prettier-java 1.6.2 (prettier 2.3.1), I have got a _lexing error_ :
```java 
import java.util.regex.Pattern;

public class Test {

  public static final String REGEX = "^\s$";

}
```

The error is : 
```
$ npx prettier --check Test.java 
Checking formatting...
Test.java[error] Test.java: Error: Sad sad panda, lexing errors detected in line: 5, column: 38!
[error] unexpected character: ->"<- at offset: 91, skipped 1 characters.
[error]     at Object.parse (/tmp/test/node_modules/java-parser/src/index.js:18:11)
[error]     at Object.parse (/tmp/test/node_modules/prettier-plugin-java/dist/parser.js:4:26)
[error]     at Object.parse$a [as parse] (/tmp/test/node_modules/prettier/index.js:13652:19)
[error]     at coreFormat (/tmp/test/node_modules/prettier/index.js:15183:16)
[error]     at formatWithCursor$1 (/tmp/test/node_modules/prettier/index.js:15423:14)
[error]     at Object.formatWithCursor (/tmp/test/node_modules/prettier/index.js:60171:12)
[error]     at format$1 (/tmp/test/node_modules/prettier/bin-prettier.js:16640:21)
[error]     at Object.formatFiles$1 [as formatFiles] (/tmp/test/node_modules/prettier/bin-prettier.js:16754:22)
[error]     at async main (/tmp/test/node_modules/prettier/bin-prettier.js:18616:5)
[error]     at async Object.run (/tmp/test/node_modules/prettier/bin-prettier.js:18559:5)
All matched files use Prettier code style!
```

**Comment by marcwrobel** [comment]
Interestingly, there is no issue if I change the regex to `"^\\s$"`.

**Comment by clementdessoude** [comment]
Hi @marcwrobel ! 

Thank you for reporting this ! Looks like we forgot the escaped space from the available escaped sequences. Should be good with #543 !

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's a bug
