### ISSUE TITLE
Sad sad panda when formatting code containing a regex (`".*\"test\"\s*:\s*\"[a-z]+\".*"`)

### ISSUE THREAD

**Issue by marcwrobel** [jhipster/prettier-java#544]
When formatting a java file that contains the following code with prettier-java 1.6.2 (prettier 2.3.1), I have got a _lexing error_ :
```java 
public class Test {

  public static final String REGEX = ".*\"test\"\s*:\s*\"[a-z]+\".*";

}
```

The error is : 
```
$ npx prettier --check /tmp/Test.java 
Checking formatting...
Test.java[error] Test.java: Error: Sad sad panda, lexing errors detected in line: 3, column: 38!
[error] unexpected character: ->"<- at offset: 58, skipped 1 characters.
[error]     at Object.parse (/tmp/node_modules/java-parser/src/index.js:18:11)
[error]     at Object.parse (/tmp/node_modules/prettier-plugin-java/dist/parser.js:4:26)
[error]     at Object.parse$a [as parse] (/tmp/node_modules/prettier/index.js:13652:19)
[error]     at coreFormat (/tmp/node_modules/prettier/index.js:15183:16)
[error]     at formatWithCursor$1 (/tmp/node_modules/prettier/index.js:15423:14)
[error]     at Object.formatWithCursor (/tmp/node_modules/prettier/index.js:60171:12)
[error]     at format$1 (/tmp/node_modules/prettier/bin-prettier.js:16640:21)
[error]     at Object.formatFiles$1 [as formatFiles] (/tmp/node_modules/prettier/bin-prettier.js:16754:22)
[error]     at async main (/tmp/node_modules/prettier/bin-prettier.js:18616:5)
[error]     at async Object.run (/tmp/node_modules/prettier/bin-prettier.js:18559:5)
All matched files use Prettier code style!
```

**Comment by marcwrobel** [comment]
Same error with `.*\"[a-z]\"\s*:.*`, but works with `.*\"[a-z]\":.*` (`\s*` removed) or `".*\"[a-z]\"a*:.*"` (`\s` replaced by `a`).

**Comment by clementdessoude** [comment]
I think this is the same issue as #541, it was an issue with parsing of the \s sequence in strings. I will release a new version of the plugin this weekend to make available the fix.

However, if I may put my two cents in, I am not sure that the regex is doing what you want, you may need to add another `\` before your `\s` to catch any whitespace character. Otherwise, your regex is equivalent as `.*\"[a-z]\" *:.*`

Here is a small test to illustrate the difference between "\\s" and "\s" :)

```java
package fr.bpifrance.tokens;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class RegexTest {

    @ParameterizedTest
    @ValueSource(strings = {"\t", "\n", " ", "\r", "\f"})
    void should_match_regex(String whitespace) {
        String anyWhiteSpaceRegex = "\\s";

        assertThat(whitespace.matches(anyWhiteSpaceRegex)).isTrue();
    }

    @ParameterizedTest
    @ValueSource(strings = {"\t", "\n", "\r", "\f"})
    void should_not_match_regex(String whitespace) {
        String spaceRegex = "\s";

        assertThat(whitespace.matches(spaceRegex)).isFalse();
    }

    @Test
    void should_not_match_regex() {
        String spaceRegex = "\s";

        assertThat(" ".matches(spaceRegex)).isTrue();
    }
}

```

**Comment by marcwrobel** [comment]
Hi @clementdessoude, you are right, this is the same bug and I made the same mistake that led to the creation of #541 (forgot to escape the `\`). I should not code when I am tired and it is late ;). Sorry for the lost time.
