### ISSUE TITLE
Not accepting a supplier as argument.

### ISSUE THREAD

**Issue by mshima** [jhipster/prettier-java#545]
**Prettier-Java 0.5.1**

```sh
# Options (if any):
--print-width 80
```

**Input:**

```java
log.debug("REST request to get FieldTestServiceClassAndJpaFilteringEntities by criteria: {}", () => criteria.toString().replaceAll("[\n\r\t]", "_"));
```

**Output:**

```sh
ERROR! Error parsing file src/main/java/tech/jhipster/sample/web/rest/FieldTestServiceClassAndJpaFilteringEntityResource.java: Error: Sad sad panda, parsing errors detected in line: 154, column: 102!
[2007](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2008)
Expecting: one of these possible Token sequences:
[2008](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2009)
  1. ['(']
[2009](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2010)
  2. [Identifier]
[2010](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2011)
  3. ['UnaryPrefixOperator']
[2011](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2012)
  4. ['DecimalLiteral']
[2012](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2013)
  5. ['HexLiteral']
[2013](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2014)
  6. ['OctalLiteral']
[2014](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2015)
  7. ['BinaryLiteral']
[2015](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2016)
  8. ['FloatLiteral']
[2016](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2017)
  9. ['HexFloatLiteral']
[2017](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2018)
  10. ['true']
[2018](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2019)
  11. ['false']
[2019](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2020)
  12. ['CharLiteral']
[2020](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2021)
  13. ['TextBlock']
[2021](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2022)
  14. ['StringLiteral']
[2022](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2023)
  15. ['null']
[2023](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2024)
  16. ['this']
[2024](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2025)
  17. ['void']
[2025](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2026)
  18. ['byte']
[2026](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2027)
  19. ['short']
[2027](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2028)
  20. ['int']
[2028](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2029)
  21. ['long']
[2029](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2030)
  22. ['char']
[2030](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2031)
  23. ['float']
[2031](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2032)
  24. ['double']
[2032](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2033)
  25. ['boolean']
[2033](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2034)
  26. ['@']
[2034](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2035)
  27. [Identifier]
[2035](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2036)
  28. ['super']
[2036](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2037)
  29. ['(']
[2037](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2038)
  30. ['new']
[2038](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2039)
  31. ['switch']
[2039](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2040)
but found: ')'!
[2040](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2041)
	->compilationUnit
[2041](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2042)
	->ordinaryCompilationUnit
[2042](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2043)
	->typeDeclaration
[2043](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2044)
	->classDeclaration
[2044](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2045)
	->normalClassDeclaration
[2045](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2046)
	->classBody
[2046](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2047)
	->classBodyDeclaration
[2047](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2048)
	->classMemberDeclaration
[2048](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2049)
	->methodDeclaration
[2049](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2050)
	->methodBody
[2050](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2051)
	->block
[2051](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2052)
	->blockStatements
[2052](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2053)
	->blockStatement
[2053](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2054)
	->statement
[2054](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2055)
	->statementWithoutTrailingSubstatement
[2055](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2056)
	->expressionStatement
[2056](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2057)
	->statementExpression
[2057](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2058)
	->expression
[2058](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2059)
	->ternaryExpression
[2059](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2060)
	->binaryExpression
[2060](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2061)
	->unaryExpression
[2061](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2062)
	->primary
[2062](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2063)
	->primarySuffix
[2063](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2064)
	->methodInvocationSuffix
[2064](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2065)
	->argumentList
[2065](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2066)
	->expression
[2066](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2067)
	->ternaryExpression
[2067](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2068)
	->binaryExpression
[2068](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2069)
	->unaryExpression
[2069](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2070)
	->primary
[2070](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2071)
	->primaryPrefix
[2071](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2072)
	->parenthesisExpression
[2072](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2073)
	->expression
[2073](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2074)
    at Object.parse (/home/runner/work/generator-jhipster/generator-jhipster/generator-jhipster/node_modules/java-parser/src/index.js:41:11)
[2074](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2075)
    at Object.parse (/home/runner/work/generator-jhipster/generator-jhipster/generator-jhipster/node_modules/prettier-plugin-java/dist/parser.js:4:26)
[2075](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2076)
    at Object.parse (/home/runner/work/generator-jhipster/generator-jhipster/generator-jhipster/node_modules/prettier/index.js:7334:23)
[2076](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2077)
    at coreFormat (/home/runner/work/generator-jhipster/generator-jhipster/generator-jhipster/node_modules/prettier/index.js:8645:18)
[2077](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2078)
    at formatWithCursor2 (/home/runner/work/generator-jhipster/generator-jhipster/generator-jhipster/node_modules/prettier/index.js:8837:18)
[2078](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2079)
    at /home/runner/work/generator-jhipster/generator-jhipster/generator-jhipster/node_modules/prettier/index.js:37229:12
[2079](https://github.com/jhipster/generator-jhipster/runs/7601230336?check_suite_focus=true#step:14:2080)
    at Object.format (/home/runner/work/generator-jhipster/generator-jhipster/generator-jhipster/node_modules/prettier/index.js:37243:12)
```

**Expected behavior:**

Should not fail.

**Comment by mshima** [comment]
Error is happening at https://github.com/jhipster/generator-jhipster/pull/19292.

**Comment by clementdessoude** [comment]
Hi @mshima ! Shouldn't it be a `->` instead of a `=>` ?

**Comment by mshima** [comment]
Indeed thanks @clementdessoude
